# Generated by Django 4.2.11 on 2025-03-03 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_movie_duration_remove_movie_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='movie',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='bookings.movie'),
            preserve_default=False,
        ),
    ]
